# Will build your gradle project and archive the output jar files.
name: Build and Archive Gradle Project

# This action will run every time you push to the "main" branch.
on:
  push:
    branches:
    - "main"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - uses: actions/upload-artifact@v3
        with:
          name: build-outputs
          path: build/libs/*.jar
